version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - API_TOKEN=my-secret-api-token-2025
    depends_on:
      - catalog
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cart
      - order

  catalog:
    build: ./catalog
    depends_on:
      - mongo-primary
    ports:
      - "3001:3001"

  cart:
    build: ./cart
    environment:
      - API_TOKEN=my-secret-api-token-2025
    depends_on:
      - catalog
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order:
    build: ./order
    environment:
      - API_TOKEN=my-secret-api-token-2025
    depends_on:
      - cart
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notification:
    build: ./notification
    depends_on:
      - rabbitmq

  mongo-primary:
    image: mongo
    container_name: mongo-primary
    ports:
      - "27017:27017"
    volumes:
      - mongo_primary_data:/data/db
    command: ["mongod", "--replSet", "rs0"]

  mongo-secondary:
    image: mongo
    container_name: mongo-secondary
    ports:
      - "27018:27017"
    volumes:
      - mongo_secondary_data:/data/db
    command: ["mongod", "--replSet", "rs0"]

  mongo-arbiter:
    image: mongo
    container_name: mongo-arbiter
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
    mongo_primary_data:
    mongo_secondary_data: